version: '3.4'

services:
  pipelineproject:
    image: pipelineproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.0.3
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: